### PR TITLE
Feat mobile menu

### PR DESCRIPTION
**Pull request by mikeyrayvon**
not in the design but i think this works better than what we have

### CODE REVIEW

**Comment by mixcas** [comment]
Code and functionality is fine but idk if the design is right. IMO it feels odd that links in the menu are not centered



@mikeyrayvon You are the designer, if u decided it will be like that feel free to push the button :)

**Comment by mikeyrayvon** [comment]
yea . there are some spacing and font size changes in the style-blog branch.  i was waiting for that to merge before doing any more style work on this

**Comment by mikeyrayvon** [comment]
but yea it should be centered i agree

**Comment by mixcas** [comment]
kk, will merge as is and make a new task to finish it

**Comment by mixcas** [comment]
@mikeyrayvon this has some conflicts, could u fix em and push plz?

i will be glad to push the button

**Pull request merged**
